# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71698f6169c6231e106f3d990190fddfbde6b6644c7cd7426fdf31f0675c23003e4c04eaa24cb8124f649bb0eb3bef4d49995253e461e5cc256a9a1f44f94c8

test:
  secret_key_base: 5b7cd030929f26e9009b4ff8f200a3472aba78c84113d618b8724dda9d9d92eef51c6e5e2a60d343fb68a98cad2c0317db03e051b66613831e76b21f64c09926

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
